### ISSUE TITLE
Trabajo y cultura

### ISSUE THREAD

**Issue by melisaeli** [SistemasInformacionComisionIII2016/LASDIVINAS#9]

**Comment by barby15** [comment]
COMERCIO ELECTRÓNICO 
El comercio electrónico se refiere al uso de Internet y Web para realizar transacciones de negocios. Dicho de una manera más formal, trata sobre las transacciones comerciales con capacidad digital entre organizaciones e individuos. En su mayor parte, esto se refiere a las negociaciones que ocurren a través de Internet y Web. Las transacciones comerciales involucran el intercambio de valor (es decir, dinero) a través de los límites organizacionales o individuales, a cambio de productos y servicios.
[…] empezó en 1995 cuando uno de los primeros portales de Internet, Netscape.com, aceptó los primeros anuncios de ciertas corporaciones importantes y popularizó la idea de que el servicio Web se podría utilizar como un nuevo medio de publicidad y ventas. Nadie imaginó en ese momento lo que resultaría ser una curva de crecimiento exponencial para las ventas minoristas de comercio electrónico, que se duplicaron y triplicaron en los primeros años.
